### PR TITLE
Add show content near me toggle to content search page

### PR DESCRIPTION
**Pull request by awel1122**
# Add show near me toggle to content search page

## Changes
     - adds show content near me toggler to conent search page and get user position.
     - adds user coordinates to the request parameters if near me toggler is checked.

### [Trello ticket #371](https://trello.com/c/6EwJyY0B/371-k%C3%A4ytt%C3%A4j%C3%A4-n%C3%A4kee-h%C3%A4nt%C3%A4-l%C3%A4hell%C3%A4-olevat-tapahtumat-harrastukset-koulutukset)

-----------------------------------------------------------------------------------------------
### Breakdown:

 1. src/views/EventListing/__snapshots__/EventListing.test.js.snap
     * updates EventListing snapshot
   
 2. src/views/Search/Search.test.js
     * adds test related to show near me toggler
    
 3. src/views/Search/__snapshots__/Search.test.js.snap
     * updates Search snapshots
     
 4. src/views/Search/index.js 
     * adds show near me toggle to Search page
   
 5. src/views/Search/index.scss
     * adds styles related to show near me toggler

### CODE REVIEW

**Review by DelusionCB — COMMENTED** [review]
Displaying events near my coordinates works like charm!

Does this really need an external library (React-switch)? This could be done with one checkbox instead of using an external library.

**Comment by jopesy** [comment]
> Displaying events near my coordinates works like charm!
> 
> Does this really need an external library (React-switch)? This could be done with one checkbox instead of using an external library.

It's not required but we wanted the switch to grab the user's attention instead of using a simple checkbox. The component also seems accessible and the library well-maintained so we didn't see a problem with that either.

**Comment by DelusionCB** [comment]
> > Displaying events near my coordinates works like charm!
> > Does this really need an external library (React-switch)? This could be done with one checkbox instead of using an external library.
> 
> It's not required but we wanted the switch to grab the user's attention instead of using a simple checkbox. The component also seems accessible and the library well-maintained so we didn't see a problem with that either.

Linked events is not meant to be users place for event searching nor information. It's only for creation & management. Calendars are the displaying layer where users attention should be captured.

I suggest the react-switch is removed & changed to normal HelCheckbox instead.

**Comment by jopesy** [comment]
> > > Displaying events near my coordinates works like charm!
> > > Does this really need an external library (React-switch)? This could be done with one checkbox instead of using an external library.
> > 
> > 
> > It's not required but we wanted the switch to grab the user's attention instead of using a simple checkbox. The component also seems accessible and the library well-maintained so we didn't see a problem with that either.
> 
> Linked events is not meant to be users place for event searching nor information. It's only for creation & management. Calendars are the displaying layer where users attention should be captured.
> 
> I suggest the react-switch is removed & changed to normal HelCheckbox instead.

That should be an easy change. I'll leave this one for Awel to decide

**Comment by awel1122** [comment]
> That should be an easy change. I'll leave this one for Awel to decide

changed to input checkbox and accessibility tested.

**Review by DelusionCB — APPROVED** [review]
LGTM!

**Pull request merged**
