### PR TITLE
Feature/filter media by organization

### PR DESCRIPTION
**Pull request by awel1122**
# Filter media by publisher in Manage media page

## Changes
     * Replace the multi-level (hierarchical) organization select with a simple select element for better accessibility.
     * Adds filtering media by publisher in Manage media page using the organization select.
     * Adds optional publisher parameter to fetching of Images from endpoint
     * Fixes Manage media navigation mobile view alignment

### [Trello card #385](https://trello.com/c/a3Wyr7MX/385-managing-images-filtering-images-by-organization) [#391](https://trello.com/c/RVe04Ede/391-accessibility-changing-publisher-for-filtering-content-not-fulfilling-requirements-for-wcag-2x)

-----------------------------------------------------------------------------------------------
### Breakdown:

 1. src/actions/userImages.js
     * Adds optional publisher parameter to fetching images
   
 2. src/components/ImageGalleryGrid/index.js
     * Adds multilevel organization select on Manage media image gallery grid
    
 3. src/components/ImageGalleryGrid/index.scss
     * Adds styling to publisher filter in Image gallery grid
     
 4. src/components/ImageGalleryGrid/tests/ImageGalleryGrid.test.js
     * Adds publisher fliter related test to Image gallery grid
     
 5. src/views/Media/ManageMedia.js
     * Adds publisher filter related props
     
 6. src/views/Media/ManageMedia.test.js
     * Adds test related to publisher filter
     
 7. src/views/Media/__snapshots__/ManageMedia.test.js.snap
    * updates ManageMedia snapshots
    
 8. src/views/Search/__snapshots__/Search.test.js.snap
     * updates Search snapshots

 9. package.json
    * Remove react-dropdown-tree-select from dependencies

10. src/components/MultiLevelSelect/* -> src/components/MultiSelect/* 
    * Renamed the component

11. src/utils/helpers.js
    * Modified the organization data formatting helper used by the organization selects

12. src/views/EventListing/*
   * Used MultiLevel component instead of MultiLevelSelect
   
13. src/components/Header/index.js
   * changes unused className to id
   
14. src/components/Header/Header.test.js
   * updates test to use id to select element

### CODE REVIEW

**Review by DelusionCB — CHANGES_REQUESTED** [review]
image
Missing form label.

**Comment by awel1122** [comment]
> Missing form label.

missing labels added to both organization selections.

**Review by DelusionCB — CHANGES_REQUESTED** [review]
image
Fieldset is missing legend & contrast is too low to pass WCAG 2.X requirements when publisher is selected.

**Comment by jopesy** [comment]
> image Fieldset is missing legend & contrast is too low to pass WCAG 2.X requirements when publisher is selected.

We'll look into this, thanks! Btw, which tools are you using and would recommend for checking the accessibility complies to WCAG 2.X? Is that Wave you're using there?

**Comment by DelusionCB** [comment]
> > image Fieldset is missing legend & contrast is too low to pass WCAG 2.X requirements when publisher is selected.
> 
> We'll look into this, thanks! Btw, which tools are you using and would recommend for checking the accessibility complies to WCAG 2.X? Is that Wave you're using there?

Wave yes.

**Comment by jopesy** [comment]
@DelusionCB This is ready for re-review now

**Review by hienous — CHANGES_REQUESTED** [review]
Seems okay but i think the nav link should be aligned with the other links. Removing the .media rule from className seems to fix it. 
image

image

**Comment by awel1122** [comment]
> Seems okay but i think the nav link should be aligned with the other links. Removing the .media rule from className seems to fix it.
Fixed as below.
manage-media-alignment

**Review by hienous — APPROVED** [review]

**Pull request merged**
